- .github/workflows/continuous-integration.yml
> AWS ECR -> GHCR

- .github/workflows/continuous-integration.yml
- package.json
* Test that Production Builds work before trying to `docker build`
* Only allow 1 docker build at a time
* But cancel any in progress builds (only build the latest)
* If you push multiple commits to a branch successively, it doesn't
really make sense to build all of them, so just build the latest
> CI: Test that Production Builds work

- helm/trust-registry/Chart.lock
- helm/trust-registry/Chart.yaml
- helm/trust-registry/conf/dev/values.yaml
- helm/trust-registry/values.yaml
* Bitnami/common `2.4.0` -> `2.8.0`
* Bitnami/mongodb `13.16.0` -> `13.16.3`
* Disable `initContainers` in Dev only
> Chore: Bump Helm Chart dependencies

- .github/workflows/continuous-integration.yml
- Tiltfile
- docker-compose.yaml
- src/server.ts
* For consistency, Compose/Tilt will run production builds
* Update MongoDB to 7.0 in CI and Compose
> Update Tilt and Compose

- Dockerfile
This should solve CI failures https://github.com/didx-xyz/ssi-trust-registry/actions/runs/6023789780/job/16341232491
> Fix docker build by adding dependencies

- .github/workflows/continuous-deploy.yml
- .github/workflows/continuous-integration.yml
- Dockerfile
* Bump `actions/checkout@v3` -> `v4`
* Bump Tailscale `1.46.1` -> `1.48.1`
* Bump Helm `v3.12.2` -> `v3.12.3`
* Bump Helmfile `v0.155.1` -> `v0.156.0`
* Build and test all PRs against `main`
* Don't push PRs
* After building docker images, run `docker compose up` and run some
very basic tests
* Migrate Dockerfile from Alpine to `debian-slim` to resolve Askar
dynamic linking
* Also multi-stage to try and keep image size down
> Add docker compose to CI pipeline

- helm/trust-registry/values.yaml
* Create an empty dir mount at `/home/node/afj`
> Helm Ephemeral `/home/node/afj` volume

- package.json
- yarn.lock
Replaces #86 #85 #82 #81 at once
I just wanted to make sure that the app really works. It works, at least on my machine :)
> Update AFJ and related libs

- .github/workflows/ci-cd.yml
- Dockerfile
- docker-compose.yaml
- helm/trust-registry.yaml
- helm/trust-registry/conf/prod/values.yaml
* Don't deploy on PR
* On PR, diff against dev
* On merge, apply to dev
* On release, apply to prod
* Initial Prod Helm config
> Prod CI/CD

- helm/trust-registry.yaml
- helm/trust-registry/Chart.lock
- helm/trust-registry/Chart.yaml
- helm/trust-registry/templates/deployment.yaml
- helm/trust-registry/templates/ingress.yaml
- helm/trust-registry/templates/secret.yaml
- helm/trust-registry/values.yaml
* Bump `bitnami/common@2.10.0` -> `bitnami/common@2.11.1`
* Bump `bitnami/mongodb@13.18.1` -> `bitnami/mongodb@13.18.4`
* Add ability to toggle DataDog APM injection
* Disabled for now
* `yarn global add node-gyp` in Dockerfile build stage
> Configure DataDog Injection

- .github/workflows/ci-cd.yml
* Install `node-gyp` in Test stage of CICD
* Bump Helm and Tailscale
> Install `node-gyp` in CICD

- .github/workflows/ci-cd.yml
- helm/trust-registry/Chart.lock
- helm/trust-registry/Chart.yaml
- helm/trust-registry/values.yaml
* Bump `bitnami/common`
* Bump `bitnami/mongodb`
* Add empty dir volumes for yarn
> Add Yarn empty dir volumes

- packages/frontend/src/app/schemas/page.tsx
- packages/frontend/src/common/interfaces.ts
> feat: list of schemas UI

- Trust Registry.postman_collection.json
Postman collection designed to help with development for now, can be improved later to send to clients.
> feat: add postman collection

- packages/frontend/src/app/invitations/page.tsx
- packages/frontend/src/app/page.tsx
- packages/frontend/src/app/schemas/page.tsx
- packages/frontend/src/app/submissions/components/SubmissionsTable.tsx
- packages/frontend/src/common/components/Table.tsx
> feat: table row hover effect

- helm/trust-registry/Chart.lock
- helm/trust-registry/Chart.yaml
- helm/trust-registry/conf/dev/values.yaml
- helm/trust-registry/conf/prod/values.yaml
- helm/trust-registry/templates/deployment.yaml
- helm/trust-registry/templates/ingress.yaml
- helm/trust-registry/templates/service.yaml
- helm/trust-registry/values.yaml
* Bump `bitnami/mongodb`
* Add config for `FRONTEND_URL` and `NEXT_PUBLIC_BACKEND_URL`
* Add necessary Ingress and Service changes to correctly route Frontend/Backend
* Bump Datadog JSLib
> Update Helm chart with Backend/Frontend config

- packages/frontend/src/app/[id]/page.tsx
- packages/frontend/src/app/components/TrustRegistryTable.tsx
- packages/frontend/src/app/page.tsx
- packages/frontend/src/common/components/Typography.tsx
> feat: entity details page

- packages/frontend/package.json
- packages/frontend/src/api.ts
- packages/frontend/src/app/layout.tsx
- yarn.lock
Use package [next-runtime-env](https://github.com/expatfile/next-runtime-env) to expose runtime environment variables to the client.
Adheres to the principle of _build once, deploy anywhere_
_Note: This means all pages have to be dynamically rendered, instead of static_
> feat: runtime client environment variables

- packages/backend/src/context.ts
- packages/backend/src/email/client-stub.ts
- packages/backend/src/email/client.ts
- packages/backend/src/email/helpers.ts
- packages/backend/src/email/service.ts
- packages/backend/src/server.test.ts
- packages/backend/src/submission/controller.ts
https://github.com/didx-xyz/ssi-trust-registry/pull/198#discussion_r1447619185
Addressing the comment made above
> refactor: email service

- .github/workflows/ci-cd.yml
* Also bump Helm, Helmfile, and Tailscale
> Don't Deploy to EKS if Github Actor is Dependabot
